# Generated by Django 5.0.6 on 2024-06-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="my_places",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_name", models.CharField(max_length=50)),
                ("location_description", models.TextField()),
                ("location_image", models.ImageField(upload_to="place_images")),
            ],
        ),
    ]
