# Generated by Django 5.0.6 on 2024-06-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="my_places",
            name="location_image",
            field=models.ImageField(blank=True, null=True, upload_to="place_images"),
        ),
    ]
