# Generated by Django 5.0.6 on 2024-06-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_my_places_location_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="my_places",
            name="age",
            field=models.IntegerField(default=55),
            preserve_default=False,
        ),
    ]
