# Generated by Django 5.0.6 on 2024-06-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_my_places_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="my_places",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "customer"),
                    ("manager", "manager"),
                    ("student", "student"),
                ],
                default="student",
                max_length=50,
            ),
        ),
    ]
