# Generated by Django 5.0.6 on 2024-06-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_my_places_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="my_places",
            name="sub_total",
            field=models.FloatField(default=5),
        ),
    ]
