# Generated by Django 5.0.6 on 2024-06-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_my_places_sub_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="my_places",
            name="interests",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
