# Generated by Django 5.0.6 on 2024-06-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_my_places_interests"),
    ]

    operations = [
        migrations.AddField(
            model_name="my_places",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
