# Generated by Django 5.0.6 on 2024-06-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_my_places_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="my_places",
            name="birthday",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="my_places",
            name="joined",
            field=models.DateField(blank=True, null=True),
        ),
    ]
